#Disabling rubocop on missing top level class documentation comment.
Style/Documentation:
  Enabled: false
#Disabling rubocop for missing frozen string literal comment.
Style/FrozenStringLiteralComment:
  Enabled: false
#Increase line length from 80 chars
Metrics/LineLength:
  Max: 100

AllCops:
  Exclude:
    - db/schema.rb
