# Find out more about the rubocop cops  https://github.com/bbatsov/rubocop/blob/master/config/enabled.yml

# inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - db/**/*
    - spec/**/*
    - config/**/*
    - bin/**/*

Layout/LineLength:
  Max: 120

Layout/EndOfLine:
  EnforcedStyle: lf

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Rails:
  Enabled: true

Rails/Date:
  Enabled: true

