services:
  db:
    image: postgres:17-bookworm
    ports:
      - 5433:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: tail -f /dev/null
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - .:/planner
      - gem_cache:/usr/local/bundle/gems
    ports:
      - 3000:3000
    depends_on:
      - db

volumes:
  db_data:
  gem_cache:
