development: &default
  adapter: postgresql
  encoding: unicode
  database: planner_development
  pool: 5
  username: <%= ENV['DB_USER'] || ''  %>
  password: <%= ENV['POSTGRES_PASSWORD'] || '' %>
  host: <%= (ENV['DB_HOST'] || 'localhost').to_json %>
  port: <%= ENV['DB_PORT'] || 5432 %>

test:
  <<: *default
  database: planner_test<%= ENV['TEST_ENV_NUMBER'] %>
  pool: 5
