# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b21f674f463fd5b1bb6b3d84a5ed71c8cd28052d8391997f851b70da9502ba740d180fcf7dd754a71fef52902a6a1768ea59c7b1d4f887e69ba58eb9fc01fa4

test:
  secret_key_base: 7112f0bb63bc6d81c4ee4182960cc7d939afbd15724b04b21e70e4a2ecb70e2aac0c5f60d0fed868f84d5c06b8fce27906f40c489aedb3181d1fc688e7ac9a25

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
