name: Docker

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - uses: docker/setup-buildx-action@v1
    - uses: docker/build-push-action@v2
      with:
        context: .
        cache-from: type=gha
        cache-to: type=gha,mode=max
    - name: Build image
      run: bin/dbuild
    - name: Run tests
      run: bin/drake
